name: Download
on:
  schedule:
    - cron: '45 4 * * *'
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{secrets.GH_TOKEN}}
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Run ExtensionsDownloader
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python ExtensionsDownloader.py
      - name: Commit And Push
        run: |
          date "+%Y-%m-%d %H:%M:%S" > timestamp
          git config user.name ${{github.repository_owner}}
          git config user.email ${{github.repository_owner}}@users.noreply.github.com
          git remote set-url origin https://${{secrets.GH_TOKEN}}@github.com/${{github.repository}}.git
          git add -A
          git commit -m "Update"
          git push -f origin ${{github.ref_name}}
